### ISSUE TITLE
Application Exit Crash

### ISSUE THREAD

**Issue by TheRandomosity** [pbhogan/InControlSupport#1]
Steps to recreate
    - Create new Unity project (Unity version 5.3.4f1)
    - Import InControl (version 1.6.0 build 7982)
    - Click Edit > Project Settings > InControl > Setup InputManager Settings
    - Create empty game object and add In Control Manager component
    - Enable Native Input and disable XInput Support
    - Connect three Xbox 360/One controllers (Definitely crashes with three wireless 360, two wireless 360 and one wired, or two wireless 360 and one wireless Xbox One)
    - Run Unity project and as soon as it has finished loading, stop it.

Crashes the Unity editor or standalone build.

**Comment by pbhogan** [comment]
Closing. Will reopen if issue continues with new build.
