### ISSUE TITLE
DeviceClass / DeviceStyle

### ISSUE THREAD

**Issue by Alloc86** [pbhogan/InControlSupport#34]
Hi Patrick,

noticed you added DeviceClass and DeviceStyle, which is really cool. Can probably get away from our own style detection soon that way :)

On a quick look though I noticed that at least the Unity profile Xbox360WinProfile doesn't specify the style / class. Maybe others too. Of course especially with such big ones missing using those values can give wrong results in the game. Was this just a mistake or is there a reason behind it?
Maybe if it's just a mistake you could set Style/Class on the base class InputDeviceProfile to something like Style.Undefined / Class.Undefined and then override it in every single subclass to either a real style/class or Unknown. That way one could easily go through all profiles by code and check if they have a style/class defined or if setting it was forgotten?

Regards,
Chris

**Comment by pbhogan** [comment]
It's just a mistake. I'll fix that for the next update.

The profile base class sets `InputDeviceClass.Unknown` and `InputDeviceStyle.Unknown` as defaults which gets overridden. Some profiles only sets `InputDeviceClass.Controller` and leaves the style unknown if it's not obviously one of the list, the intention being for the developer to choose a default behavior for `.Unknown`, which may vary on platform or personal preference. I don't know if I would go all the way to having an `.Undefined` setting and checking it by code, but it's something to consider.

**Comment by Alloc86** [comment]
Cool, thanks for the heads up :)
