### ISSUE TITLE
Maybe bug, disconnect and connect a controller is still alive

### ISSUE THREAD

**Issue by everalan10** [pbhogan/InControlSupport#35]
Hi!

We are fascinated with your plugin because you saved us a lot of work. We are using this plugin in [Mulaka](http://www.lienzo.mx/mulaka) for the four consoles and we think that the bug when disconnect and connect a controller is still alive.

Our setup:

- **InControl 1.6.17**
- Unity **5.5.4p5** or **5.5.5p2**
- We have two PlayerActionSet instances (**UIControls** and **GameplayControls**).
- We `UIControls.Enable = true/false;` between instances when user is in UI's menus or gameplay.
- A USB Xbox One controller.

How to reproduce:

1. In Main Menu the **UIControls** and **GameplayControls** instances were created.
2. Select one game level to play.
3. In middle of gameplay if we disconnect and connect the Xbox One controller, in a few seconds the application crashes and exit.

> What could we do?
> 	Maybe subscribe to `InputManager.OnDeviceDetached` to do something.

Thanks for you time.

**Comment by everalan10** [comment]
My apologies, we were working very hard to fix our problem and it is already done!
The problem was in one script dedicated for another platform controller, but must only be in that platform not in PC.

**Comment by pbhogan** [comment]
No problem—glad it was solved!
